### ISSUE TITLE
Custom Formatter Failed: ReferenceError: bindRemoteObject is not defined

### ISSUE THREAD

**Issue by danielcompton** [binaryage/dirac#20]
Often when I try to expand large CLJS objects in the devtools console I get this error:

```
Custom Formatter Failed: ReferenceError: bindRemoteObject is not defined
load	@	VM3277:9
```

Is there anything I can do to help track it down?

**Comment by darwin** [comment]
Seems to be another incarnation of https://github.com/binaryage/cljs-devtools/issues/14.

Could be related to their work 
https://bugs.chromium.org/p/chromium/issues/detail?id=595206#c26

They are still messing with command-line API and moving it to native implementation. It looks you hit some corner case which is still broken due to recent changes.

**Comment by danielcompton** [comment]
I'm running 
<img width="278" alt="screenshot of google chrome 27-05-16 9-28-23 am" src="https://cloud.githubusercontent.com/assets/811954/15590764/60ddef42-23ed-11e6-99e2-d963c5bde50a.png">

I could still reproduce the issue after starting with a fresh profile.

**Comment by Producr** [comment]
Just a heads up. Still broken on Version 53.0.2751.0 canary (64-bit).

**Comment by darwin** [comment]
maybe it is time to reopen
https://bugs.chromium.org/p/chromium/issues/detail?id=599884 ?

**Comment by danielcompton** [comment]
Probably a good idea.

**Comment by darwin** [comment]
Technically this is not Dirac issue, but cljs-devtools one.

I have reopened https://github.com/binaryage/cljs-devtools/issues/14, let's move there.
