### ISSUE TITLE
Stack trace formatting removes name of function when calling multi arity functions 

### ISSUE THREAD

**Issue by danielcompton** [binaryage/dirac#25]
Dirac 0.6.0

<img width="405" alt="screenshot of google chrome 7-06-16 10-52-35 am" src="https://cloud.githubusercontent.com/assets/811954/15840428/03a23c34-2c9e-11e6-9b91-89a0349a470f.png">

it looks like Dirac is stripping the name of the function if a multi arity function is called?

`3 @ core.cljs:4621` corresponds to 

```
(defn into
  "Returns a new coll consisting of to-coll with all of the items of
  from-coll conjoined. A transducer may be supplied."
  ([to from]
     (if-not (nil? to)
       (if (implements? IEditableCollection to)
         (with-meta (persistent! (reduce -conj! (transient to) from)) (meta to))
         (reduce -conj to from))
       (reduce conj () from)))
  ([to xform from]
     (if (implements? IEditableCollection to)
>>>>   (with-meta (persistent! (transduce xform conj! (transient to) from)) (meta to))
       (transduce xform conj to from))))
```

**Comment by darwin** [comment]
I see. The problem is extra dollar in the name of those functions. It breaks on this line:
https://github.com/binaryage/dirac/blob/a6a5a807bf6655a43ed744b833da9354d3f1754b/src/implant/dirac/implant/munging.cljs#L11

That function has to smarter. Unfortunately namespace separators seem are just dollars and there is no simple way how to distinguish them from dollars used in function names by user.

**Comment by danielcompton** [comment]
Just one note, the dollar is part of CLJS compiler output for multi arity functions, it's not a function name from the user.

**Comment by darwin** [comment]
Still the same issue. I take last $ in the name and treat part after it as short name without namespace.

A quick workaround: Disable "Beautify function names" in Dirac Extension options on chrome://extensions page.

**Comment by danielcompton** [comment]
Great, can do!
