### ISSUE TITLE
Different keyboard command for switching between console types

### ISSUE THREAD

**Issue by danielcompton** [binaryage/dirac#9]
On my keyboard, I don't have the Page Up and Page Down key bound to their respective keys. It would be handy to be able to provide either a button, or another key command to toggle between the two consoles.

**Comment by darwin** [comment]
Using a macbook? You can do `PageUp` using `Fn + Up Arrow`[1].

I have just tested it here with my macbook and it works with Dirac REPL Prompt.

I want to keep two keyboard shortcuts for next/prev prompt, because I expect possible support for more REPL prompts in the future (e.g. one for js, one for cljs, and maybe additional for clojure REPLs or some other nREPL connections).

[1] http://osxdaily.com/2015/07/07/page-up-page-down-mac-keyboard/

**Comment by danielcompton** [comment]
I'm on an external keyboard without PageUp/Down mapped. Being able to provide a custom command like Ctrl+Up/Ctrl+Down or similar would be ideal for my use case.

**Comment by darwin** [comment]
The problem is that I'm using DevTools' own "_registerShortcuts" infrastructure here[1]. They don't seem to offer user-configurable keyboard shortcuts, they hard-code their own shortcuts there as well (maybe sometimes just testing for current OS). I would have to build an UI for that or build that UI in Dirac Extension and propagate that config into DevTools. That sounds like a dull job and something prone to breaking the minute I forget that something like this exists.

I would recommend you to find a way how to map page up and page down on your external keyboard. There must be some way - page up/down are quite useful keys :-)

[1] https://github.com/binaryage/dirac/blob/b433537213b20e730bae376ebc453e4315fd2408/resources/unpacked/devtools/front_end/console/ConsoleView.js#L1026-L1027

**Comment by danielcompton** [comment]
Sure thing, I'll figure something out :)

**Comment by stumitchell** [comment]
Hi im hit by this to on the chromebook pixel. Perhaps you can follow devtools lead and offer two options (like F12 and ctrl-shift i)
maybe 
PageUp = control+>
PageDown = control+<

**Comment by darwin** [comment]
Ok, I will reconsider this for next release.
